global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ian-platform'
    region: 'south-africa'
    environment: 'development'

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: 'reference-app'
    static_configs:
      - targets: ['reference-app:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - target_label: service
        replacement: 'reference-app'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - target_label: service
        replacement: 'system'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
