services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change-me-in-env
    volumes:
      - gateway-keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--import-realm"]
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9000:9000"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change-me-in-env
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: change-me-in-env
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ../keycloak/realm:/opt/keycloak/data/import:ro

  reference-app:
    build:
      context: ../../services/reference-app

  gateway:
    build: .
    depends_on:
      - keycloak
      - reference-app
    environment:
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/master
      UPSTREAM_URL: http://reference-app:5000
    ports:
      - "8081:8081"

volumes:
  gateway-keycloak-postgres:
